dist: bionic
env:
 global:
  - DEBIAN_FRONTEND=noninteractive
before_install:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('root') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade -u root -p123123
  - sudo service mysql restart
  - composer global require hirak/prestissimo
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.1.0-amd64.deb
  - sudo dpkg -i --force-confnew elasticsearch-7.1.0-amd64.deb
  - sudo sed -i.old 's/-Xms1g/-Xms128m/' /etc/elasticsearch/jvm.options
  - sudo sed -i.old 's/-Xmx1g/-Xmx128m/' /etc/elasticsearch/jvm.options
  - echo -e '-XX:+DisableExplicitGC\n-Djdk.io.permissionsUseCanonicalPath=true\n-Dlog4j.skipJansi=true\n-server\n' | sudo tee -a /etc/elasticsearch/jvm.options
  - sudo chown -R elasticsearch:elasticsearch /etc/default/elasticsearch
  - sudo service elasticsearch restart
language: php
php:
  - 7.4
services:
  - mysql
  - docker
cache:
  directories:
    - node_modules
before_script:
  - until curl --silent -XGET --fail http://localhost:9200; do printf '.'; sleep 1; done
  - cp .env.example .env
  - sudo mysql -uroot -proot -e 'CREATE DATABASE laravel;'
  - sudo mysql -uroot -proot -e "CREATE USER 'keller'@'localhost' IDENTIFIED BY 'password';"
  - sudo mysql -uroot -proot -e "GRANT ALL ON laravel.* TO 'keller'@'localhost';"
  - composer self-update
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer install --prefer-dist --no-interaction
  - php artisan key:generate
  - php artisan migrate
script:
  - vendor/bin/phpunit
  - sh/pipeline/backend_db_clone.sh
after_success:
        #  - docker --version
        #  - pip install --user awscli
        #  - export PATH=$PATH:$HOME/.local/bin
        #  - eval $(aws ecr get-login --no-include-email --region us-west-2)
        #  - docker pull 963713796187.dkr.ecr.us-west-2.amazonaws.com/pipeline/minio:latest
