sudo: required
dist: bionic
env:
 global:
  - DEBIAN_FRONTEND=noninteractive
before_install:
  - composer global require hirak/prestissimo
language: php
php:
  - 7.4
services:
  - mysql
  - docker
cache:
  directories:
    - node_modules
    - vendor
before_script:
  - cp .env.example .env
  - sudo mysql -e 'CREATE DATABASE laravel;'
  - sudo mysql -e "CREATE USER 'keller'@'localhost' IDENTIFIED BY 'password';"
  - sudo mysql -e "GRANT ALL ON laravel.* TO 'keller'@'localhost';"
  - composer self-update
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer install --prefer-dist --no-interaction
  - php artisan key:generate
  - php artisan migrate
script:
  - vendor/bin/phpunit
after_success:
  - docker --version
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - eval $(aws ecr get-login --no-include-email --region us-west-2)
  - docker pull 963713796187.dkr.ecr.us-west-2.amazonaws.com/pipeline/minio:latest
