dist: bionic
env:
 global:
  - DEBIAN_FRONTEND=noninteractive
before_install:
  - composer global require hirak/prestissimo
language: php
php:
  - 7.4
services:
  - mysql
cache:
  directories:
    - node_modules
    - vendor
before_script:
  - cp .env.example .env
  - sudo mysql -e 'CREATE DATABASE laravel;'
  - sudo mysql -e "CREATE USER 'keller'@'localhost' IDENTIFIED BY 'password';"
  - sudo mysql -e "GRANT ALL ON laravel.* TO 'keller'@'localhost';"
  - composer self-update
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer install --prefer-dist --no-interaction
  - php artisan key:generate
  - php artisan migrate
script:
  - vendor/bin/phpunit
