dist: bionic
git:
  submodules:
    false
before_install:
  - echo -e "machine bitbucket.org\n  login $BITBUCKET_USER_NAME\n  password $BITBUCKET_USER_PASSWORD" >~/.netrc
  - git submodule update --init --recursive
language: php
php:
  - 7.4
services:
  - mysql
cache:
  directories:
    - node_modules
    - vendor
before_script:
  - cp .env.example .env
  - sudo mysql -e 'create database laravel;'
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - php artisan key:generate
  - php artisan migrate
script:
  - vendor/bin/phpunit
