dist: bionic
env:
 global:
  - DEBIAN_FRONTEND=noninteractive
before_install:
  - sudo apt-get update
  - sudo LC_ALL=C.UTF-8 add-apt-repository -y ppa:ondrej/php
  - sudo apt-get update
  - sudo apt-get install -y software-properties-common
  - sudo apt-get install -y --no-install-recommends php7.4-cli php7.4-dev php7.4-pgsql php7.4-sqlite3 php7.4-gd
  - sudo apt-get install -y --no-install-recommends php7.4-curl php7.4-memcached php7.4-imap php7.4-mysql php7.4-mbstring
  - sudo apt-get install -y --no-install-recommends php7.4-xml php7.4-imagick php7.4-zip php7.4-bcmath php7.4-soap
  - sudo apt-get install -y --no-install-recommends php7.4-intl php7.4-readline php-pcov
  - sudo apt-get install -y gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3
  - sudo apt-get install -y libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4
  - sudo apt-get install -y libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1
  - sudo apt-get install -ylibxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6
  - sudo apt-get install -y ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils
  - sudo apt-get install -y git libicu-dev zlib1g-dev supervisor vim
  - sudo apt-get install -y libxrender1 libfontconfig1 libx11-dev libjpeg62 libxtst6 xfonts-75dpi libpng-dev
  - sudo apt-get install -y gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3
  - sudo apt-get install -y libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4
  - sudo apt-get install -y libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1
  - sudo apt-get install -y libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6
  - sudo apt-get install -y ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils build-essential
language: php
php:
  - 7.4
services:
  - mysql
cache:
  directories:
    - node_modules
    - vendor
before_script:
  - cp .env.example .env
  - sudo mysql -e 'create database laravel;'
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - php artisan key:generate
  - php artisan migrate
script:
  - vendor/bin/phpunit
