dist: bionic
addons:
  apt:
    packages:
      - sshpass
env:
  global:
  - DEBIAN_FRONTEND=noninteractive
before_install:
- openssl aes-256-cbc -K $encrypted_dfdcfd5172af_key -iv $encrypted_dfdcfd5172af_iv
  -in deploy_key.enc -out ./deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host $HOSTNAME_STAGING\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
- sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('root')
  where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
- sudo mysql_upgrade -u root -proot
- sudo service mysql restart
- composer global require hirak/prestissimo
language: php
php:
- 7.4
services:
- mysql
- docker
install:
- cp .env.example .env
- sudo mysql -uroot -proot -e 'CREATE DATABASE laravel;'
- sudo mysql -uroot -proot -e "CREATE USER 'keller'@'localhost' IDENTIFIED BY 'password';"
- sudo mysql -uroot -proot -e "GRANT ALL ON laravel.* TO 'keller'@'localhost';"
- composer self-update
- COMPOSER_MEMORY_LIMIT=-1 travis_retry composer install --prefer-dist --no-interaction
- php artisan key:generate
- php artisan migrate
jobs:
  include:
  - stage: Tests
    name: Backend Tests
    script:
    - echo "backend test 1"
    - echo "backend test 2"
  - script:
    - echo "frontend test 1"
    - echo "frontend test 2"
    name: Frontend Tests
  - stage: Deploy
    env:
      - AWS_ACCESS_KEY_ID=$TEST1
      - AWS_SECRET_ACCESS_KEY=$TEST2
    name: Deploy to staging
    install: skip
    script:
    - if [[ $TRAVIS_BRANCH == "staging" ]] ; then echo "Testing brach $TRAVIS_BRANCH"
      ; fi
    - sed -i "s#CDN_URL=.*#CDN_URL=$CDN_LINK#g" .env.example
    - sed -i "s#APP_ENV=.*#APP_ENV=$TRAVIS_BRANCH#g" .env.example
    - aws s3 cp server.php s3://tcpdftest
after_success:
- docker --version
