name: Pipeline-Tests

on:
  pull_request:
    branches: [ master ]
  workflow_call:
  workflow_dispatch:

defaults:
  run:
    shell: bash

# -------------------------------------------------
# Concurrency rules.....
# -------------------------------------------------

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

# -------------------------------------------------
# Jobs
# -------------------------------------------------

jobs:
  changed_backend:
    runs-on: pipeline
    if: github.event_name != 'schedule' && github.event_name != 'workflow_dispatch'
    outputs:
      backend_changed: ${{ steps.filter.outputs.backend }}
    steps:
      - name: Backend changes 🚗
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            backend:
              - 'Dockerfile'
              - 'composer.json'
              - 'composer.lock'
              - '**/*.php'
              - '**/*.sql'
              - '*.xml'
              - '**/*.yml'
              - '*.neon'
              - '**/*.sh'
              - 'devops/docker/*'

  changed_frontend:
    runs-on: pipeline
    if: github.event_name != 'schedule' && github.event_name != 'workflow_dispatch'
    outputs:
      frontend_changed: ${{ steps.filter.outputs.frontend }}
      frontend_exclude: ${{ steps.filter.outputs.exclude }}
    steps:
      - name: Frontend changes 🚗
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            frontend:
              - 'package.json'
              - 'yarn.lock'
              - '**/*.js'
              - '**/*.ts'
              - '**/*.html'
              - '**/*.css'
              - '**/*.scss'
              - '**/*.yml'
              - '**/*.json'
              - '**/*.sh'
            exclude:
              - 'tests/Cypress/**/*.po.ts'
              - 'tests/Cypress/**/*.host.ts'
              - 'tests/Cypress/**/*.spec.ts'
              - '.github/workflows/production.yml'
              - '.github/workflows/staging.yml'

  changed_e2e:
    runs-on: pipeline
    if: github.event_name != 'schedule' && github.event_name != 'workflow_dispatch'
    outputs:
      e2e_changed: ${{ steps.filter.outputs.e2e }}
    steps:
      - name: E2E changes 🚗
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            e2e:
              - 'package.json'
              - 'yarn.lock'
              - 'tests/Protractor/**/*.js'
              - 'tests/Cypress/**/*.ts'
              - 'tests/Cypress/**/*.json'
              - 'tests/Wdio/**/*.ts'
              - 'tests/Wdio/**/*.json'
              - 'devops/docker/**/*'

  changed_general:
    runs-on: pipeline
    if: github.event_name != 'schedule' && github.event_name != 'workflow_dispatch'
    outputs:
      general_changed: ${{ steps.filter.outputs.general }}
    steps:
      - name: General changes 🚗
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            general:
              - 'Dockerfile'
              - 'composer.json'
              - 'composer.lock'
              - 'package.json'
              - 'yarn.lock'
              - '**/*.php'
              - '**/*.sql'
              - '*.xml'
              - '**/*.yml'
              - '**/*.sh'
              - '**/*.js'
              - 'resources/**/!(*.spec|*.po|*.host).ts'
              - 'tests/Cypress/**/*.ts'
              - '*.ts'
              - '**/*.html'
              - '**/*.css'
              - '**/*.scss'
              - '**/*.json'

  backend_test:
    runs-on: pipeline
    needs: [changed_backend]
      #    if: (needs.changed_backend.outputs.backend_changed == 'true') || (github.event_name == 'pull_request' && github.event.action == 'closed') || (always() && !cancelled() && github.event_name == 'workflow_dispatch')
    if: (needs.changed_backend.outputs.backend_changed == 'true') || (github.event_name == 'pull_request' && github.event.action == 'closed') || (always() && !cancelled() && github.event_name == 'schedule')
    steps:
      - name: Checkout
        run: |
            echo "Checkout"
      - name: Backend test 🚗
        run: |
            echo "Run Backend test"
            sleep 100500
            echo "event name is:" ${{ github.event_name }}
            echo "event type is:" ${{ github.event.action }}

  frontend_build:
    runs-on: pipeline
    needs: [changed_general]
      #    if: (needs.changed_general.outputs.general_changed == 'true' && github.event_name == 'pull_request' && github.event.action != 'closed') || (always() && !cancelled() && github.event_name == 'workflow_dispatch')
    if: (needs.changed_general.outputs.general_changed == 'true' && github.event_name == 'pull_request' && github.event.action != 'closed') || (always() && !cancelled() && github.event_name == 'schedule')
    steps:
      - name: Checkout
        run: |
            echo "Checkout"
      - name: Frontend Build 🚗
        run: |
            echo "Run Frontend Build"

  frontend_test:
    runs-on: pipeline
    needs: [changed_frontend]
    if: (needs.changed_frontend.outputs.frontend_changed == 'true') || (github.event_name == 'pull_request' && github.event.action == 'closed') || (always() && !cancelled() && github.event_name == 'schedule')
    steps:
      - name: Checkout
        run: |
            echo "Checkout"
      - name: Frontend test 🚗
        run: |
            echo "Run Frontend test"

  e2e_cypress_prepare:
    runs-on: pipeline
    needs: [changed_general]
    if: (needs.changed_general.outputs.general_changed == 'true' && github.event_name == 'pull_request' && github.event.action != 'closed') || (always() && !cancelled() && github.event_name == 'schedule')
    steps:
      - name: Checkout
        run: |
            echo "Checkout"
      - name: E2E Cypress prepare 🚗
        run: |
            echo "Run E2E Cypress prepare"

  e2e_cypress:
    needs: [changed_general, e2e_cypress_prepare, frontend_build]
    if: (needs.changed_general.outputs.general_changed == 'true' && github.event_name == 'pull_request' && github.event.action != 'closed') || (always() && !cancelled() && github.event_name == 'schedule')
    runs-on: pipeline
    steps:
      - name: Checkout
        run: |
            echo "Checkout"
      - name: E2E Cypress 🚗
        run: |
            echo "E2E Cypress"
