name: Production deployment

on:
  release:
    types: [created]

jobs:
  production_prepare:
    runs-on: self-hosted
    steps:
      - name: Checkout 👀
        uses: actions/checkout@v3
        with:
          fetch-depth: 10
          lfs: false
      - name: Production prepare 🚗
        run: |
            echo "Tag name from github.ref_name: ${{  github.ref_name }}"
            cat test.txt
