name: Production deployment

on:
  release:
    types: [created]

jobs:
  production_prepare:
    runs-on: self-hosted
    steps:
      - name: Checkout 👀
        uses: actions/checkout@v3
        with:
          fetch-depth: 10
          lfs: false
      - name: Production prepare 🚗
        run: |
            git checkout -f ${{ github.event.inputs.commit }}
            echo "Production prepare."
            echo "The commit SHA is ${{ github.event.inputs.commit }}"
            cat test.txt
            git switch -
