name: Production deployment

on:
  release:
    types: [created]

jobs:
  production_prepare:
    runs-on: self-hosted
    steps:
      - name: Checkout 👀
        uses: actions/checkout@v3
        with:
          fetch-depth: 10
          lfs: false
      - name: Production prepare 🚗
        run: |
            TAG=${{ github.ref }}
            TAG=${{ TAG/refs\/tags\// }}
            echo "Selected tag: $TAG"
            cat test.txt
