name: Production deployment

on:
  release:
    types: [created]

jobs:
  production_prepare:
    runs-on: self-hosted
    steps:
      - name: Checkout 👀
        uses: actions/checkout@v3
        with:
          fetch-depth: 10
          lfs: false
      - name: Production prepare 🚗
        run: |
            TTT=$( echo ${{ github.ref_name }} )
            echo $TTT
            cat test.txt
