name: Nightly

on:
  schedule:
    - cron:  '*/5 * * * *'

defaults:
  run:
    shell: bash

jobs:
  swagger:
    if: github.event.schedule == '*/5 * * * *'
    uses: ./.github/workflows/pipeline.yml

